name: Deploy

on:
  push:
    branches:
      - main

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Pull Docker Image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/mspilot-frontend:latest

      - name: Verify Pulled Docker Image
        run: |
          docker images
      - name: Build Frontend
        run: |
          yarn install
          yarn build
      - name: Deploy Frontend to the Server
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
          heroku_email: "yasser.abassi.ya@gmail.com"
