name: Deploy

on:
  push:
    branches:
      - main

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify Frontend Directory
        run: |
          ls -la
      - name: Build Frontend
        run: |
          npm install
          npm run build
      - name: Deploy to Heroku Frontend
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
          heroku_email: "yasser.abassi.ya@gmail.com"